import { Event, EventRegistration } from './events.model';

// =============================================
//  Mock Events Data (UI-only, no backend)
// =============================================

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    name: 'Swimming Championship 2026',
    description: 'Annual inter-club swimming championship open to all competitive swimmers.',
    startDate: '2026-05-28T09:00:00',
    endDate: '2026-05-28T18:00:00',
    venue: 'Main Branch Pool',
    capacity: 50,
    registrationsCount: 30,
    accessType: 'MembersOnly',
    status: 'Published',
    imageUrl: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&auto=format',
    badge: 'Championship',
    pricingPolicyIds: [],
    ticketTypes: [
      {
        id: 'tt1',
        eventId: '1',
        category: 'Member',
        basePrice: 0,
        totalQuantity: 30,
        availableQuantity: 12,
        maxPerMember: 1,
        requiresMembership: true,
        minAge: 12,
        maxAge: null,
        genderRestriction: null,
      },
      {
        id: 'tt2',
        eventId: '1',
        category: 'Guest',
        basePrice: 150,
        totalQuantity: 20,
        availableQuantity: 8,
        maxPerMember: 2,
        requiresMembership: false,
        minAge: null,
        maxAge: null,
        genderRestriction: null,
      },
    ],
  },
  {
    id: '2',
    name: 'Ramadan Family Fitness Camp',
    description: 'A special fitness camp designed for the whole family during Ramadan.',
    startDate: '2026-06-01T08:00:00',
    endDate: '2026-06-10T12:00:00',
    venue: 'Sport Hall A',
    capacity: 80,
    registrationsCount: 55,
    accessType: 'MembersOnly',
    status: 'Published',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&auto=format',
    badge: 'Ramadan Special',
    pricingPolicyIds: [],
    ticketTypes: [
      {
        id: 'tt3',
        eventId: '2',
        category: 'Member',
        basePrice: 200,
        totalQuantity: 50,
        availableQuantity: 20,
        maxPerMember: 1,
        requiresMembership: true,
        minAge: 18,
        maxAge: 60,
        genderRestriction: null,
      },
      {
        id: 'tt4',
        eventId: '2',
        category: 'FamilyMember',
        basePrice: 100,
        totalQuantity: 30,
        availableQuantity: 5,
        maxPerMember: 4,
        requiresMembership: false,
        minAge: 6,
        maxAge: null,
        genderRestriction: null,
      },
    ],
  },
  {
    id: '3',
    name: 'Youth Basketball Tournament',
    description: 'Open youth basketball tournament for ages 10-18. Teams of 5 players.',
    startDate: '2026-07-15T10:00:00',
    endDate: '2026-07-15T20:00:00',
    venue: 'Indoor Court B',
    capacity: 100,
    registrationsCount: 0,
    accessType: 'Public',
    status: 'Draft',
    imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&auto=format',
    badge: null,
    pricingPolicyIds: [],
    ticketTypes: [],
  },
  {
    id: '4',
    name: 'Women\'s Yoga Retreat',
    description: 'A relaxing full-day yoga retreat for female members.',
    startDate: '2026-08-20T09:00:00',
    endDate: '2026-08-20T17:00:00',
    venue: 'Wellness Studio',
    capacity: 30,
    registrationsCount: 0,
    accessType: 'MembersOnly',
    status: 'Draft',
    imageUrl: 'https://images.unsplash.com/photo-1588286840104-8957b019727f?w=800&auto=format',
    badge: null,
    pricingPolicyIds: [],
    ticketTypes: [
      {
        id: 'tt5',
        eventId: '4',
        category: 'Member',
        basePrice: 350,
        totalQuantity: 30,
        availableQuantity: 30,
        maxPerMember: 1,
        requiresMembership: true,
        minAge: 16,
        maxAge: null,
        genderRestriction: 'Female',
      },
    ],
  },
  {
    id: '5',
    name: 'Spring Marathon 5K',
    description: 'Community 5K run open to everyone. Certificates for all finishers!',
    startDate: '2026-04-10T07:00:00',
    endDate: '2026-04-10T12:00:00',
    venue: 'Corniche Road',
    capacity: 200,
    registrationsCount: 180,
    accessType: 'Public',
    status: 'Cancelled',
    imageUrl: 'https://images.unsplash.com/photo-1533560904424-a0c61dc306fc?w=800&auto=format',
    badge: null,
    pricingPolicyIds: [],
    ticketTypes: [],
  },
];

// =============================================
//  Mock Registrations (for event id '1')
// =============================================

export const MOCK_REGISTRATIONS: EventRegistration[] = [
  {
    id: 'reg1',
    eventId: '1',
    registrantName: 'Ahmed Hassan',
    registrantInitials: 'AH',
    status: 'Confirmed',
    attendeeCount: 3,
    totalPrice: 300,
    appliedPolicies: ['Family Discount'],
    attendees: [
      { id: 'a1', name: 'Ahmed Hassan', ticketCategory: 'Member', age: 34, gender: 'Male' },
      { id: 'a2', name: 'Sara Hassan', ticketCategory: 'FamilyMember', age: 30, gender: 'Female' },
      { id: 'a3', name: 'Ali Hassan', ticketCategory: 'FamilyMember', age: 10, gender: 'Male' },
    ],
  },
  {
    id: 'reg2',
    eventId: '1',
    registrantName: 'Mohamed Karim',
    registrantInitials: 'MK',
    status: 'PendingPayment',
    attendeeCount: 1,
    totalPrice: 150,
    appliedPolicies: [],
    attendees: [
      { id: 'a4', name: 'Mohamed Karim', ticketCategory: 'Guest', age: 28, gender: 'Male' },
    ],
  },
  {
    id: 'reg3',
    eventId: '1',
    registrantName: 'Nadia Salah',
    registrantInitials: 'NS',
    status: 'Confirmed',
    attendeeCount: 2,
    totalPrice: 0,
    appliedPolicies: [],
    attendees: [
      { id: 'a5', name: 'Nadia Salah', ticketCategory: 'Member', age: 25, gender: 'Female' },
      { id: 'a6', name: 'Laila Salah', ticketCategory: 'FamilyMember', age: 8, gender: 'Female' },
    ],
  },
  {
    id: 'reg4',
    eventId: '1',
    registrantName: 'Omar Ibrahim',
    registrantInitials: 'OI',
    status: 'Cancelled',
    attendeeCount: 1,
    totalPrice: 150,
    appliedPolicies: [],
    attendees: [
      { id: 'a7', name: 'Omar Ibrahim', ticketCategory: 'Guest', age: 32, gender: 'Male' },
    ],
  },
];
